# World bank indicator # annual
VIET_NAM_ID = 'VNM'
USA_ID = 'USA'
CHINA_ID = 'CHN'
GDP_GROWTH = 'NY.GDP.MKTP.KD.ZG'
REAL_INTEREST_RATE = 'FR.INR.RINR'
UNEMPLOYMENT_RATE = 'SL.UEM.TOTL.ZS'
INFLATION = 'FP.CPI.TOTL.ZG'
CURRENT_ACCOUNT_BALANCE = 'BN.CAB.XOKA.CD'
GOVERNMENT_DEBT = 'GC.DOD.TOTL.GD.ZS'

# Yahoo finance
BRENT_OIL = 'BZ=F'
GOLD = 'GC=F'
VIX = '^VIX'
SP500 = '^GSPC'
DOWJONES = '^DJI'
SHANGHAI = '000001.SS'
HANGSENG = '^HSI'
NIKKEI = '^N225'
KOSPI = '^KS11'
DXY = 'DX-Y.NYB'
BTC = 'BTC-USD'
ETH = 'ETH-USD'

# vnstock 
VNINDEX = 'VNINDEX'
USDVND = 'USDVND'
CNYVND = 'CNYVND'

# simplize
CHUNK_SIZE = 50

LOAD_TIME_DATA_CHUNK_SIZE = 100